### ISSUE TITLE
Can not access Wireguard dashboard when I am connected to it

### ISSUE THREAD

**Issue by OteroQA** [wg-easy/wg-easy#1012]
**Describe the bug**
I have a Raspberry Pi with Pi-hole and WireGuard installed on the fixed IP address 192.168.1.10. I am connected to the Raspberry's VPN on my regular PC, and I can't access the Pi-hole or WireGuard dashboard, whereas I used to do so using the Raspberry's IP 192.168.1.10 followed by the port of each service.

For example:

If I am not connected to the VPN on my PC, I can access Portainer through https://192.168.1.10:9443/

I can access WireGuard through http://192.168.1.10:51821/

However, when I am connected to the VPN and try to enter both sites through Google Chrome, it tells me the following: 

> Your Internet access is blocked. The firewall or antivirus software may have blocked the connection.
> Try to:
> 
> Check the connection
> Check the firewall and antivirus settings
> Run Windows Network Diagnostics
> ERR_NETWORK_ACCESS_DENIED

Meanwhile, from an iOS mobile connected to the VPN, I can access that IP.

I attach here the docker yml conf as a txt.
[docker-compose.txt](https://github.com/wg-easy/wg-easy/files/15153668/docker-compose.txt)

**Comment by OteroQA** [comment]
I fixed the issue on PC editing the tunnel file directly putting:

`AllowedIPs = 10.8.0.4/32, 10.8.1.0/24, 192.168.1.0/24`

Is there any way to fix this directly without changing any conf on the wireguard PC app?

![2024-04-29_21h16_17](https://github.com/wg-easy/wg-easy/assets/56387207/617e2217-1545-4c4a-84f7-3f1f9c19d493)

**Comment by eandersons** [comment]
You can predefine allowed IPs with `WG_ALLOWED_IPS` if all clients are supposed to have the same value, otherwise you will have to manually edit allowed IPs in Wireguard application on clients when needed as currently it is not possible to specify allowed IPs in WireGuard Eeasy interface for each client separately.

Another option is to download client configuration from WireGuard Easy interface an manually edit allowed IPs before giving it to the intended user.

**Comment by Baxit360** [comment]
> `WG_ALLOWED_IPS`

But a client can easy edit the config file and update it as 0.0.0.0/24

**Comment by pheiduck** [comment]
Try v13 it has a fix for that issue.
