### ISSUE TITLE
Port forwarding doesn't work arter latest update

### ISSUE THREAD

**Issue by MolodoGvardeets** [wg-easy/wg-easy#1120]
Port forwarding does not work after the update. Previously, I used ports 51831 for webui, 51830 for wg. I indicated it at the beginning, and then through the option -p 51831:51821 and -p 51830:51820. Webui is working, wg is not connected. What could be the problem?
And also, how to use password_hash? I don't have a password entry window, it goes directly to the page.

**Comment by TheHexaMaster** [comment]
Hi, i solved similiar issue direct changing WG ports to ports that you want to use (- PORT= 51830 and - WG_PORT= 51831) and open docker ports straight (-p 51831:51831 and -p 51830:51830). Try, it shall help.

About password protection, if you want to use direct passphrase, use PASSWORD instead of PASSWORD_HASH

**Comment by MolodoGvardeets** [comment]
Thanks! Work now!
