### ISSUE TITLE
Bug when setting password

### ISSUE THREAD

**Issue by samuellhwarren** [wg-easy/wg-easy#1124]
I have the password set, but when I enter it, i get an error on the web interface saying "incorrect password"

Installed using this:
`version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${WG_HOST}

      # Optional:
      - PASSWORD=9^jKy8%!q$FUuV #will change this later 
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /somevolume/wireguard:/etc/wireguard
    ports:
      - "${WG_PORT}:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
`

**Comment by eandersons** [comment]
That is because your password contains `$`, and Compose parses `$FUuV` as a variable, therefore the actual password being used is `9^jKy8%!q`, as the variable `$FUuV` does not exist and as a result `$FUuV` is replaced with an empty value.

If password (or any other value) contains `$`, it should be escaped with another `$`: `9^jKy8%!q$$FUuV`.

**Comment by samuellhwarren** [comment]
Ok, that makes sense…
