### ISSUE TITLE
Add support for non-/24 subnets

### ISSUE THREAD

**Issue by rijenkii** [wg-easy/wg-easy#140]
As of now you can only specify /24 subnets in WG_DEFAULT_ADDRESS. 254 IP addresses are insufficient for my use case.

It would be better to allow users to specify the subnet not in "192.168.0.x" format, but in "192.168.0.0/24" format, allowing for more flexibility.

**Comment by whatdemocracy** [comment]
I agree. Would be also possible subnets?

**Comment by whatdemocracy** [comment]
I agree. It'd be more scalable...

**Comment by WeeJeWel** [comment]
It would be, but would make setting up harder for new users..

**Comment by rijenkii** [comment]
It's always possible to support both formats.

**Comment by smilence86** [comment]
Yes, I faced it and got this error:
```
Error: inet prefix is expected rather than "172.16.0.1/21/24"
```

Hope to support two formats allow user use it what he want :)

**Comment by TimonLukas** [comment]
I just implemented this in an internal fork I'm building for a company-internal VPN. I can't share the changed code, but it was pretty simple - instead of [generating the IP naively using a loop](https://github.com/WeeJeWel/wg-easy/blob/master/src/lib/WireGuard.js#L230-L240) I pre-generate a list of all possible IP addresses using [`netmask`](https://www.npmjs.com/package/netmask), from which I then pick the next available one. There were a couple of places I had to update since they per default include the `/24` part, but it's working pretty well now!

If you want to keep compatibility with both methods, I'd either advise to check for `x` in `DEFAULT_ADDRESSES`, if it's there execute the existing logic, if not use the netmask logic; or you could change it to instead be the starting IP, and if there's no netmask it will automatically assume `/24`. Both ways should work pretty well, though the earlier would be either to migrate to.

**Comment by templehasfallen** [comment]
Also interested in this.
Seems when providing a CIDR it simply errors out as it just appends `/24` to the address.
It's not so much of a change to provide `192.168.0.0/24` instead of `192.168.0.x` for `DEFAULT_ADDRESSES` and it would at best moderately heighten the difficulty.
Alternatively, check the input to see if it includes a `/**` and only append `/24/` if it does not.

**Comment by BrainStone** [comment]
There you have a PR ^^

The moment you use a library stuff gets easy!

**Comment by hadleyrich** [comment]
> I just implemented this in an internal fork I'm building for a company-internal VPN. I can't share the changed code, but it was pretty simple

https://github.com/wg-easy/wg-easy/blob/master/LICENSE.md

**Comment by rijenkii** [comment]
Don't you stale on me.

**Comment by willtho89** [comment]
see #797

**Comment by pheiduck** [comment]
#888 needs some rework as it breaks Backwards compatibility.
