### ISSUE TITLE
[Bug]: Invalid interpolation format in PASSWORD_HASH for docker-compose.yml

### ISSUE THREAD

**Issue by wakko222** [wg-easy/wg-easy#1450]
### Describe the bug

ERROR: Invalid interpolation format for "environment" option in service "wg-easy"

### Expected behavior

Work just fine!

**Comment by kaaax0815** [comment]
Without your docker compose file nobody can help you

**Comment by moppman** [comment]
@wakko222 
The error message is quite expressive. It tells you that you made a mistake when you set the environment variable `PASSWORD_HASH` in your `docker-compose.yml` file.
The most likely scenario: you did not escape the `$` symbol(s) in your password hash with another `$ `in front of it. That's why the docker engine interpreted your hash as a placeholder for a variable that does not exist and thus could not replace (i.e. interpolate) it.

Please read this document that is mentioned in the README of this project: https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md
It tells you exactly how you need to set your password hash in your compose file:
>Important : Please note: don't wrap the generated hash password in single quotes when you use docker-compose.yml. Instead, replace each $ symbol with two $$ symbols.

**Comment by kaaax0815** [comment]
Already written here (with an example where `$` -> `$$`)

https://github.com/wg-easy/wg-easy/blob/e75719b8033fecb8137635883c80580db5f3a393/docker-compose.yml#L15-L15
