### ISSUE TITLE
Run the container with defined PUID and PGID?

### ISSUE THREAD

**Issue by garret** [wg-easy/wg-easy#392]
As title, is there a way to obtain it, maybe by setting up a variable like in linuxserver.io images. 

I am asking because the config folder volume is saved locally with root permissions, thus only root can eventually modify/remove it.

**Comment by shyonae** [comment]
I'm also interested in this, any updates or workarounds?

**Comment by eandersons** [comment]
Alternatives are:

- store configuration in a Docker volume (I am using this approach);
- provide configuration files with [`configs`](https://docs.docker.com/compose/compose-file/compose-file-v3/#configs) in Docker Compose file (I did not test this, so it might not work, and for this approach configuration files must be obtained first);
- manage configuration files from within the WireGuard Easy container.

The problem is that starting WireGuard Easy container with a non-root user (for example, providing `--user 1000:1000` to `docker run` or using `user: 1000:1000` in Docker Compose file) will end up with a permission error:

```
[Error: EACCES: permission denied, open '/etc/wireguard/wg0.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/etc/wireguard/wg0.json'
}
```

Theoretically WireGuard Easy container could be adjusted to run with a non-root user with the help of sudo, but in the end the user will be executing commands as root and permissions of bind-mounted files will be changed anyway, so there is no point in this.
