### ISSUE TITLE
Port cannot be changed

### ISSUE THREAD

**Issue by hoddelhs** [wg-easy/wg-easy#424]
Port is not changed, port 51820 is always used.

$ docker run -d \
  --name=wg-easy \
  -e WG_HOST=🚨YOUR_SERVER_IP \
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \
  **-p 51820:51820/udp \
  -p 51821:51821/tcp \**
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy

**Comment by eandersons** [comment]
It is not clear what exactly is the problem.

From `WG_PORT` description in [Options](/WeeJeWel/wg-easy#options):

> WireGuard will always listen on 51820 inside the Docker container.

**Comment by simon-kcse** [comment]
Yes, using `WG_PORT` would change the host port configuration for WireGuard, but the generated client config file is still using port "51820" instead of the new host port.

When I download the peer config file onto my Android phone using QR code, I can see that under `Peer`, the `Endpoint` IP address is `WG_HOST`, but the port is 51820 and not the number specified by `WG_PORT`.
