### ISSUE TITLE
Can't access home network

### ISSUE THREAD

**Issue by tiritibambix** [wg-easy/wg-easy#440]
**Describe the bug**
I successfully created several configs to connect my phone or my partner's phone to my home network and using pihole with our smartphones and it works great. I also did this with my mom's computer this summer to access my home network using the windows app. Great.

Now I'm locked at my in law's and I want to play around with my server so I grabed my partner's windows computer, downloaded the windows app, added its dedicated config and I can't access my home network.

I can browse the web, my wg says that the computer is logged in the tunnel, but I can not access my home network. I tried different browsers, tried sftp, nothing works.

I'm sure that's something dumb I can't find on her computer, but I can't put my finger on it.

What should I look for ?

Log says this : https://pastebin.com/h1C8LvF8

**To Reproduce**
1. Go to my in laws
2. Get crazy

**Desktop (please complete the following information):**
 - OS: Win 8
 - Browser : Chrome, Vivaldi and Librewolf
 - Version: latest

**Comment by DerLev** [comment]
I got the same problem and I might have a solution that works. *at least it did the trick for me*

I started trying to set the server IP in the `wg0.json` to the actual server IP which didn't do anything.

Then I moved the WireGuard server to a different subnet (from `192.168.178.x` to `192.168.2.x`) which then let me access my home LAN and the internet from my iPad as a testing device. I also changed the ip in the `wg0.json` to the new subnet respectively (`192.168.2.1`). I don't know how and why because my home network only has one subnet and vlan thanks to my restrictive router from my isp but it works now so I'm not complaining 🤷‍♂️ 

---

`wg0.json`
```json
{
  "server": {
    "privateKey": "redacted",
    "publicKey": "redacted",
    "address": "192.168.2.1"
  },
  "clients": {}
}
```
