### ISSUE TITLE
Restrict IP Forwarding with ufw

### ISSUE THREAD

**Issue by stevenay** [wg-easy/wg-easy#606]
First of all, I have experience with PiVPN WireGuard setup. Now try to setup wg-easy on Ubuntu because its UI is really useful and intuitive. 

I normally restrict specific client not allow to connect specific IP by writing ufw rule like "sudo ufw route deny in on wg0 from 10.14.77.2/32 to 10.x.x.x".

For wg-easy setup, when I check the available network interfaces, I found out that docker0 and another one named with "vethaf91bee@if6". I deny IP forwarding on both these interfaces but not working and the client can access to all IPs including Internet Access. I even defined DEFAULT_FORWARD_POLICY="DROP" at /etc/default/ufw but still not working.

 - OS: Ubuntu 22.04.2

**Comment by niggowai** [comment]
You can checkout my config,
I used the `WG_POST_UP` environment variable to setup my iptables ond override the default setting

Default:
~~~
iptables -t nat -A POSTROUTING -s ${module.exports.WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o ${module.exports.WG_DEVICE} -j MASQUERADE;
iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;
iptables -A FORWARD -i wg0 -j ACCEPT;
iptables -A FORWARD -o wg0 -j ACCEPT;
~~~

Since there are variables defined which do not get interpreted when we set the env var, we need to lets substitute them to their values, assuming you didn't set `WG_DEFAULT_ADDRESS` and 'WG_DEVICE`:

~~~
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE;
iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;
iptables -A FORWARD -i wg0 -j ACCEPT;
iptables -A FORWARD -o wg0 -j ACCEPT;
~~~

So thats my config:

~~~
services:
  wireguard:
    image: weejewel/wg-easy
    container_name: wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    environment:
      - WG_HOST=you-dont-know-my-address.org
      - PASSWORD=secret
      - WG_DEFAULT_DNS=192.168.178.39
      - WG_ALLOWED_IPS=192.168.224.0/24
      - WG_DEFAULT_ADDRESS=10.8.0.x
        # Allow only the wg_traffic network and deny http access to pihole and wg-easy Dashboard
      - WG_POST_UP=
        iptables -A FORWARD -d 192.168.224.2 -p tcp --dport 80 -j DROP;
        iptables -A INPUT -d 192.168.224.3 -p tcp --dport 51821 -j DROP;
        iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE;
        iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;
        iptables -A FORWARD -i wg0 -s 192.168.224.0/24 -j ACCEPT;
        iptables -A FORWARD -o wg0 -d 192.168.224.0/24 -j ACCEPT;
    volumes:
      - ./wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`wireguard.fritz.box`)"
      - "traefik.http.routers.wireguard.entrypoints=web"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.docker.network=traefik"
    networks:
      traefik:
      wg_traffic:
        ipv4_address: 192.168.224.3


networks:
  traefik:
    name: traefik
    external: true
  wg_traffic:
    name: wg_traffic
    external: true
~~~

`iptables -A FORWARD -d 192.168.224.2 -p tcp --dport 80 -j DROP` will block access to my pihole Dashboard,
`iptables -A INPUT -d 192.168.224.3 -p tcp --dport 51821 -j DROP` will block access to my wg-easy Dashboard
~~~
iptables -A FORWARD -i wg0 -s 192.168.224.0/24 -j ACCEPT;
iptables -A FORWARD -o wg0 -d 192.168.224.0/24 -j ACCEPT
~~~
These two rules were modified to only allow traffic from wg to a special wg_traffic docker network and vice versa

**Comment by genieai-vikas** [comment]
@niggowai  is it possible to perform below scenario using your docker compose?
- block all expect google.com
- Allow all except youtube.com

**Comment by niggowai** [comment]
I think this goes far behind the capabillities of iptables since google and yt have more than just a couple of servers running.

In my opinion, your best approach would be to either use wg-easy with an dns server like pihole as an adblocker or use a proxy server to control the http traffic.

When taking the DNS way users may be able to reach yt by using an entry in their Hosts file,

when going the Proxy way you may block traffic which is not http-based ...

**Comment by genieai-vikas** [comment]
@niggowai Thanks for help. what about split tunnelling will it be possible to access google.com via WG but when try to access yt route it outside WG when connected?

**Comment by niggowai** [comment]
Like I said, with iptables it wont be possible.

you may use split tunneling in the Wireguard app itself when you're working on mobile, or you may try to exclude/include the ip ranges of google/yt but that may result in other hosts not beeing reachable in general

**Comment by genieai-vikas** [comment]
@niggowai  I setup the WG on ec2 machine and using WG to connect mac to some of the tools. You said it's possible on mobile, is it possible in Mac/linux as well? I tired ip ranges but it won't work as I don't have all the ip ranges so dns is the only option. I searched the documentation but couldn't find help.

**Comment by niggowai** [comment]
Routing the requests outside the tunnel via dns wont work, only blocking them.
If you want to block the connection via dns you can add something like `0.0.0.0 youtube.com` in your pihole adlists.
You may only allow the Private IP-ranges of your Docker container to use the tunnel but routing websites through different connections may be out of scope of this project. If you want to use the connection to yt and google via http(s) you can setup a proxy and exclude yt from using the proxy by setting it as an excluded address in your macs proxy config
