### ISSUE TITLE
Restricting Access Using 'wg-easy' with WireGuard

### ISSUE THREAD

**Issue by genieai-vikas** [wg-easy/wg-easy#636]
Issue Description:

Background:

I'm currently exploring the capabilities of 'wg-easy' in combination with WireGuard for managing VPN connections. I have two specific access control scenarios that I'd like to implement, and I'm seeking guidance on whether 'wg-easy' supports these scenarios.

Scenarios:

Blocking Access to All Except Google and GitHub:

In this scenario, I want to configure 'wg-easy' to block access to all websites except for 'google.com' and 'github.com' when users are connected via WireGuard.
Allowing Access to All Except YouTube:

In this scenario, I aim to configure 'wg-easy' to allow access to 'google.com' via wireguard but when I access 'github.com' it should go via normal route and not via wireguard

Question:
Is it possible to achieve these access control scenarios using 'wg-easy' with WireGuard? If so, I'd appreciate guidance on how to set up the configurations to make this work effectively.

Thank you for your assistance!

**Comment by deanvz** [comment]
Nope. Wireguard is not a L7 proxy. You can set up routing to certain IP addresses and subnets, but its impossible to enumerate all the ip address google and github.com would use as you would have to do that in order to allow traffic to be routed to those endpoints via the VPN. 

You are also circumventing the need for a VPN here it seems. You would want to run wireguard in order to access local resources. Not specifically internet resources via it.

**Comment by peterlewis** [comment]
As @deanvz mentions, wg-easy would not be a suitable way for you to achieve what you are after, here. You'd be better off looking to implement DPI on your router/gateway which will do a much better (and much simpler) job at blocking specific sites.l
