### ISSUE TITLE
Unauthorised when trying to install the docker image

### ISSUE THREAD

**Issue by karl0ss** [wg-easy/wg-easy#678]
Trying to run the docker image as per the readme.md and getting 

`Error response from daemon: Head "https://ghcr.io/v2/wg-easy/wg-easy/manifests/latest": unauthorized`

**Comment by kirsysuv** [comment]
I also found this problem just now.
It seems that he docker image build action was failed and currently there is no available docker image on ghcr.io/wg-easy/wg-easy

**Comment by adityabekn** [comment]
I also got this response, I tried logging in with a personal access token from github and now the response changed from unauthorized to denied

**Comment by VoidTerror** [comment]
try replacing the line
**ghcr.io/wg-easy/wg-easy**
on
**weejewel/wg-easy**
helped me

**Comment by mezoology** [comment]
build was canceled [358](https://github.com/wg-easy/wg-easy/actions/runs/7241229828/job/19725102964#step:7:358)

**Comment by mezoology** [comment]
> try replacing the line **ghcr.io/wg-easy/wg-easy** on **weejewel/wg-easy** helped me

the `:latest` tag pushed 18 months ago. use `weejewel/wg-easy:7-nightly` instead

**Comment by mrjones-plip** [comment]
Since the repo has [the `Dockerfile` included](https://github.com/wg-easy/wg-easy/blob/master/Dockerfile), it's not too hard to just build the image locally instead of using the one normally published to the GitHub Container Repository (`ghcr.io`).  I found the [build command](https://github.com/wg-easy/wg-easy/blob/94d00166748fa1059201d2dd6ba26f9d6fc53cf3/package.json#L4) in the `package.json`. 

Here's the steps that I took which worked for me resulting in the `latest` image:

1. Clone the repo: `git clone https://github.com/wg-easy/wg-easy.git`
2. Change directories into the repo: `cd wg-easy`
3. Build the image: `docker build --tag wg-easy .`
4. Edit `docker-compose.yml` so that line 21 with `image:` looks like this: `image: wg-easy`
5. Run the compose command sending the process into the background: `docker compose up -d`

I see the one on `weejewel/wg-easy` [docker hub](https://hub.docker.com/r/weejewel/wg-easy/tags) page mentioned [above](https://github.com/wg-easy/wg-easy/issues/678#issuecomment-1861248610)  has `latest` as of ~1hr ago.  If you want to use something more current, specify the `7` as the tag to get an up to date build: 

```
image:ghcr.io/weejewel/wg-easy:7
```

Or...just wait for the build to pass in this repo ;)

Cheers!

**Comment by WeeJeWel** [comment]
Sorry, fixed! Thanks for reporting.
