### ISSUE TITLE
Can not connect to the internet

### ISSUE THREAD

**Issue by sinnayuh** [wg-easy/wg-easy#810]
**Describe the bug**
Installed WG-EASY via the docker-compose.yaml, everything installed correctly server is setup on my VPS i created a new client for my iPhone scanned the QR Code connected to the VPN and when i try goto google.com nothing happens and i timeout.

**To Reproduce**
1. Install WG-Easy on VPS
2. Goto browser and create client i.e iPhone
3. Scan QR Code on Phone and Connect
4. Goto google & timeout

**Expected behavior**
Connect successfully and browse internet

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.1.1
 - Browser Firefox

**Comment by iiiypuk** [comment]
+1

**Comment by lyf2000** [comment]
same

**Comment by iiiypuk** [comment]
WTF dislike?!

**Comment by eandersons** [comment]
> WTF dislike?!

Because of pointless comment - it does not add any additional and helpful information that could improve the chances of resolving issue nor provides a solution.
Comments like "+1" and "same" should be avoided as they just clutter space and spam e-mail for those people that are involved in or subscribed to an issue issue and meaning of such comments can simply be expressed by adding the thumbs up emoji to the first post.

**Comment by pheiduck** [comment]
@eandersons I am with you.

**Comment by ptech2009** [comment]
Pllease ensure that you forward the necessary UDP Ports not TCP!

**Comment by pheiduck** [comment]
@sinnayuh please provide your docker-compose.yml otherwise we can't help you.

**Comment by pheiduck** [comment]
And I locked the conversation now because some people abuse emoji's ^^
