### ISSUE TITLE
wg-easy command not found!

### ISSUE THREAD

**Issue by Alison110** [wg-easy/wg-easy#984]
I get this error:

docker: invalid reference format.
See 'docker run --help'.
-bash: --name=wg-easy: command not found
software caused system 
<img width="303" alt="wireguard pannel error" src="https://github.com/wg-easy/wg-easy/assets/166883333/e07e9b74-c450-446f-8e30-4db6717979ed">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ubunto 22.04

**Comment by eandersons** [comment]
The executed command seems to be correct.
You should check that there is no space after the first backslash (`docker run -d \`; and other backslashes as well), otherwise a space is escaped instead of a newline and the next line (`--name=wg-easy`) is evaluated as a separate line by shell and therefore it is run as a different command, hence the `command not found` error.

If you still do not manage to run `docker run` command successfully, you could try to:

- put the whole command in a single line and remove backslashes;
- use the [Compose file](/wg-easy/wg-easy/blob/master/docker-compose.yml) instead, adjust it to your needs and use the command `docker compose up --detach` to start the container.

**Comment by Alison110** [comment]
You're right, 🙏, thank you.
